name: omol25_db
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gettext=0.21.0
  - git=2.51.0
  - graphite2=1.3.14
  - greenlet=3.2.4
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jansson=2.14
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libboost=1.88.0
  - libboost-python=1.88.0
  - libcurl=8.17.0
  - libdeflate=1.22
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.10.8
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy-base=2.4.1
  - openbabel=3.1.1
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - perl=5.42.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.3
  - reportlab=4.4.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=2.0.45
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - ase==3.27.0
      - ase-db-backends==0.11.0
      - attrs==25.4.0
      - bibtexparser==1.4.3
      - biopython==1.86
      - certifi==2026.1.4
      - cffi==2.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - clusterscope==0.0.18
      - colorful==0.5.8
      - cryptography==46.0.3
      - distlib==0.4.0
      - e3nn==0.5.9
      - fairchem-core==2.13.0
      - fastapi==0.128.0
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - googleapis-common-protos==1.72.0
      - griddataformats==1.0.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==1.3.1
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - llvmlite==0.46.0
      - lmdb==1.7.3
      - markdown==3.10
      - markupsafe==3.0.3
      - mda-xdrlib==0.2.0
      - mdanalysis==2.10.0
      - mmtf-python==1.1.3
      - monty==2025.3.3
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.5
      - palettable==3.3.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - prometheus-client==0.24.0
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - psutil==7.2.1
      - psycopg2-binary==2.9.11
      - py-spy==0.4.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pymatgen==2025.10.7
      - pymysql==1.1.2
      - pyparsing==3.3.1
      - pyre-extensions==0.0.32
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - ray==2.53.0
      - rdkit==2025.9.5
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - rsa==4.9.1
      - ruamel-yaml==0.19.1
      - scipy==1.17.0
      - sentry-sdk==2.49.0
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - spglib==2.7.0
      - starlette==0.50.0
      - submitit==1.5.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchtnt==0.2.4
      - tqdm==4.67.1
      - triton==3.4.0
      - typer-slim==0.21.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uncertainties==3.2.4
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - virtualenv==20.36.1
      - wandb==0.23.1
      - watchfiles==1.1.1
      - websockets==16.0
      - werkzeug==3.1.5
      - wrapt==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
